':guitar: Инструменты':
- changed-files:
  - any-glob-to-any-file:
    - '.github/**/*'
    - '.vscode/**/*'
    - 'docs/**/*'
    - 'scripts/**/*'
    - 'test/**/*'
    - 'tools/**/*'
    - '.codebeatignore'
    - '.codebeatsettings'
    - '.editorconfig'
    - '.git*'
    - 'biome.json'
    - 'libmysql.dll'
    - 'LICENSE'
    - 'README.md'
    - 'SpacemanDMM.toml'

':world_map: Изменение Карты':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.dmm'

':rice: Спрайты':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.dmi'

':sound: Звуки':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.aif'
    - '**/*.aiff'
    - '**/*.it'
    - '**/*.mid'
    - '**/*.midi'
    - '**/*.mod'
    - '**/*.mp3'
    - '**/*.ogg'
    - '**/*.oxm'
    - '**/*.raw'
    - '**/*.s3m'
    - '**/*.wma'
    - '**/*.wav'
    - '**/*.xm'

':page_facing_up: Требуется изменение конфига':
- changed-files:
  - any-glob-to-any-file:
    - 'config/example/**/*'

'SQL':
- changed-files:
  - any-glob-to-any-file:
    - 'sql/**/*'

'TGUI':
- changed-files:
  - any-glob-to-any-file:
    - 'tgui/**'
