#define CLICK_HANDLER_NONE EMPTY_BITFIELD
#define CLICK_HANDLER_REMOVE_ON_MOB_LOGOUT FLAG(0)
#define CLICK_HANDLER_REMOVE_IF_NOT_TOP FLAG(1)
#define CLICK_HANDLER_ALL ( CLICK_HANDLER_REMOVE_ON_MOB_LOGOUT | CLICK_HANDLER_REMOVE_IF_NOT_TOP)
