name: "Чейнджлог: YML -> HTML"

permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # allows this workflow to be manually triggered

jobs:
  CompileCL:
    permissions:
      contents: write # required to push the updated changelog commit
    runs-on: ubuntu-latest
    if: github.repository == 'ss220club/WyccerraBay220' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0 # Otherwise, we will fail to push refs
          ref: master
          token: ${{ secrets.BOT_TOKEN }}
      - name: Python setup
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml bs4
      - name: Compile CL
        run: |
          python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit And Push
        run: |
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git config --global user.name "${{ secrets.BOT_NAME }}"
          git diff --quiet --exit-code && echo "No changes found, abort." && exit 0
          git commit -m "Автоматическая компиляция чейнджлогов [ci skip]" -a
          git push
